-- Tabela generation
CREATE TABLE generation (
    ID INTEGER PRIMARY KEY,
    NUMBERS INTEGER,
    POKEMONS INTEGER,
    LENGENDARYS INTEGER
);

-- Tabela type
CREATE TABLE type (
    ID INTEGER PRIMARY KEY,
    NAME TEXT
);

-- Tabela superefects
CREATE TABLE superefects (
    WEAKNESS INTEGER,
    STRENGTH INTEGER,
    FOREIGN KEY (WEAKNESS) REFERENCES type(ID),
    FOREIGN KEY (STRENGTH) REFERENCES type(ID)
);

-- Tabela pokemon
CREATE TABLE pokemon (
    ID INTEGER PRIMARY KEY,
    NAME TEXT,
    TYPE1 INTEGER,
    TYPE2 INTEGER,
    TOTAL INTEGER,
    HP INTEGER,
    ATTACK INTEGER,
    DEFENSE INTEGER,
    SP_ATAQUE INTEGER,
    SP_DEFENSE INTEGER,
    SPEED INTEGER,
    GENERATION INTEGER,
    LEGENDARY BOOLEAN,
    FOREIGN KEY (TYPE1) REFERENCES type(ID),
    FOREIGN KEY (TYPE2) REFERENCES type(ID),
    FOREIGN KEY (GENERATION) REFERENCES generation(ID)
);

-- Tabela mega
CREATE TABLE mega (
    ID INTEGER PRIMARY KEY,
    NAME TEXT,
    TYPE1 INTEGER,
    TYPE2 INTEGER,
    TOTAL INTEGER,
    HP INTEGER,
    ATTACK INTEGER,
    DEFENSE INTEGER,
    SP_ATAQUE INTEGER,
    SP_DEFENSE INTEGER,
    SPEED INTEGER,
    POKEMON INTEGER,
    FOREIGN KEY (TYPE1) REFERENCES type(ID),
    FOREIGN KEY (TYPE2) REFERENCES type(ID),
    FOREIGN KEY (POKEMON) REFERENCES pokemon(ID)
);